spring.data.mongodb.uri=mongodb+srv://santiago:santiago19@cluster0.b7mgq.mongodb.net/api-translate?retryWrites=true&w=majority&appName=Cluster0

# Configuración del servidor
server.port=8080
server.address=0.0.0.0
server.forward-headers-strategy=FRAMEWORK

# Configuración de la aplicación
spring.application.name=deeptraslate
app.name=Structure Microservice
app.description=API para la gestión de estructuras
app.version=1.0.0

# Configuración de logging para debug
logging.level.org.springframework.web=DEBUG
logging.level.pe.edu.vallegrande=DEBUG
