# kubectl apply -f deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeptraslate
  namespace: santiagoprada
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deeptraslate
  template:
    metadata:
      labels:
        app: deeptraslate
    spec:
      containers:
      - name: deeptraslate
        image: santiagoprada1029/deeptraslate-api:latest   # Reemplaza con tu imagen DockerHub
        imagePullPolicy: IfNotPresent           # Evita bajar la imagen si ya existe
        envFrom:
            - secretRef:
                name: credentials               # Cargar todo el Secret como variables de entorno