# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: santiagoprada
type: Opaque
data:
  # Credenciales de la base de datos y RapidAPI en Base64
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9zYW50aWFnbzpzYW50aWFnbzE5QGNsdXN0ZXIwLmI3bWdxdS5tb25nb2RiLm5ldC9hcGktdHJhbnNsYXRlP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw
  DATABASE_USERNAME: c2FudGlhZ28=
  DATABASE_PASSWORD: c2FudGlhZ28xOQ==
  RAPIDAPI_URL: aHR0cHM6Ly9kZWVwLXRyYW5zbGF0ZTEucC5yYXBpZGFwaS5jb20vbGFuZ3VhZ2UvdHJhbnNsYXRlL3Yy
  RAPIDAPI_HOST: ZGVlcC10cmFuc2xhdGUxLnAucmFwaWRhcGkuY29t
  RAPIDAPI_APIKEY: NjcxYjUwYTEyMm1zaGFmOTc2NGRhN2Q3NzM5Y3AxNzJhNzVqc25hNzVmZjFmNjZlOWI=

# echo -n "my-user" | base64
# echo -n "my-password" | base64
# echo "bXktdXNlcg==" | base64 --decode